// samples-React.js/src/samples/ExportMultiXlsx.js
import { useEffect, useRef } from 'react';
import AUIGrid from '../static/AUIGrid-React.js/AUIGridReact';
// eslint-disable-next-line
import FileSaver from 'file-saver';

const PUBLIC_URL = process.env.PUBLIC_URL;

const gridData = [
	{ id: '#Cust0', date: '2014-10-01', name: 'Steve', country: 'USA', flag: 'usa.png', product: 'IPad Air', color: 'Green', quantity: 3, price: 630700 },
	{ id: '#Cust1', date: '2014-09-30', name: 'Emma', country: 'Korea', flag: 'korea.png', product: 'LG G3', color: 'Pink', quantity: 1, price: 503800 },
	{ id: '#Cust2', date: '2014-09-29', name: 'Emma', country: 'Japan', flag: 'japan.png', product: 'IPad Air', color: 'Yellow', quantity: 7, price: 66900 },
	{ id: '#Cust3', date: '2014-09-28', name: 'Emma', country: 'UK', flag: 'uk.png', product: 'Galaxy Note3', color: 'Orange', quantity: 9, price: 458300 },
	{ id: '#Cust4', date: '2014-09-27', name: 'Anna', country: 'China', flag: 'china.png', product: 'LG G3', color: 'Violet', quantity: 10, price: 168100 },
	{ id: '#Cust5', date: '2014-09-26', name: 'Anna', country: 'USA', flag: 'usa.png', product: 'Galaxy S5', color: 'Gray', quantity: 3, price: 10400 }
];

const columnLayout = [
	{ dataField: 'id', headerText: 'ID', width: 120 },
	{ dataField: 'name', headerText: 'Name', width: 140 },
	{ dataField: 'country', headerText: 'Country', width: 140 },
	{
		dataField: 'flag',
		headerText: 'Flag IMG',
		editable: false,
		prefix: PUBLIC_URL + '/assets/',
		renderer: { type: 'ImageRenderer', imgHeight: 24, altField: 'country' },
		width: 100
	},
	{ dataField: 'product', headerText: 'Product', width: 140 },
	{ dataField: 'color', headerText: 'Color', width: 100 },
	{
		dataField: 'price',
		headerText: 'Price',
		dataType: 'numeric',
		style: 'my-column',
		width: 120,
		editRenderer: { type: 'InputEditRenderer', onlyNumeric: true, textAlign: 'right', autoThousandSeparator: true }
	},
	{
		dataField: 'quantity',
		headerText: 'Quantity',
		dataType: 'numeric',
		style: 'my-column',
		width: 100,
		editRenderer: { type: 'InputEditRenderer', onlyNumeric: true, textAlign: 'right', autoThousandSeparator: true }
	},
	{ dataField: 'date', headerText: 'Date', dataType: 'date', dateInputFormat: 'yyyy-mm-dd', formatString: 'yyyy년 mm월 dd일' }
];

const gridProps = {
	width: '100%',
	height: 280
};

const ExportMultiXlsx = () => {
	const myGrid = useRef();
	const myGrid2 = useRef();
	const myGrid3 = useRef();
	const myGrid4 = useRef();

	useEffect(() => {
		myGrid.current.setGridData(gridData);
		myGrid2.current.setGridData(gridData.slice(1, 3));
		myGrid3.current.setGridData(gridData.slice(2, 4));
		myGrid4.current.setGridData(gridData.slice(3, 5));
	}, []);

	const exportClick = () => {
		const grid = myGrid.current;
		const grid2 = myGrid2.current;
		const grid3 = myGrid3.current;
		const grid4 = myGrid4.current;

		const exportProps = [
			{
				fileName: '그리드 4개 1개의 엑셀로 저장 테스트',
				sheetName: '일반 데이터',
				progressBar: true,
				headers: [
					{ text: '원본 데이터 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			},
			{
				sheetName: 'Type 1',
				headers: [
					{ text: 'Type 1 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			},
			{
				sheetName: 'Type 2',
				headers: [
					{ text: 'Type 2 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			},
			{
				sheetName: 'Type 3',
				headers: [
					{ text: 'Type 3 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			}
		];
		grid.exportToXlsxMulti([grid2.pid, grid3.pid, grid4.pid], exportProps);
	};

	return (
		<div>
			<div className="desc">
				<button className="btn" onClick={exportClick}>
					4개 그리드 각각의 시트로 엑셀(xlsx) 저장하기
				</button>
			</div>
			<h3>그리드1</h3>
			<AUIGrid ref={myGrid} columnLayout={columnLayout} gridProps={gridProps} />
			<h3>그리드2</h3>
			<AUIGrid ref={myGrid2} columnLayout={columnLayout} gridProps={gridProps} />
			<h3>그리드3</h3>
			<AUIGrid ref={myGrid3} columnLayout={columnLayout} gridProps={gridProps} />
			<h3>그리드4</h3>
			<AUIGrid ref={myGrid4} columnLayout={columnLayout} gridProps={gridProps} />
		</div>
	);
};

export default ExportMultiXlsx;

// samples-Vue.js/src/samples/ExportMultiXlsx.vue
<script setup>
	import AUIGrid from '@/static/AUIGrid-Vue.js/AUIGrid.vue';
	import 'file-saver';
	import { ref, onMounted } from 'vue';

	const PUBLIC_URL = import.meta.env.BASE_URL;
	const myGrid1 = ref(null);
	const myGrid2 = ref(null);
	const myGrid3 = ref(null);
	const myGrid4 = ref(null);

	const gridData = [
		{ id: '#Cust0', date: '2014-10-01', name: 'Steve', country: 'USA', flag: 'usa.png', product: 'IPad Air', color: 'Green', quantity: 3, price: 630700 },
		{ id: '#Cust1', date: '2014-09-30', name: 'Emma', country: 'Korea', flag: 'korea.png', product: 'LG G3', color: 'Pink', quantity: 1, price: 503800 },
		{ id: '#Cust2', date: '2014-09-29', name: 'Emma', country: 'Japan', flag: 'japan.png', product: 'IPad Air', color: 'Yellow', quantity: 7, price: 66900 },
		{ id: '#Cust3', date: '2014-09-28', name: 'Emma', country: 'UK', flag: 'uk.png', product: 'Galaxy Note3', color: 'Orange', quantity: 9, price: 458300 },
		{ id: '#Cust4', date: '2014-09-27', name: 'Anna', country: 'China', flag: 'china.png', product: 'LG G3', color: 'Violet', quantity: 10, price: 168100 },
		{ id: '#Cust5', date: '2014-09-26', name: 'Anna', country: 'USA', flag: 'usa.png', product: 'Galaxy S5', color: 'Gray', quantity: 3, price: 10400 }
	];

	const columnLayout = [
		{ dataField: 'id', headerText: 'ID', width: 120 },
		{ dataField: 'name', headerText: 'Name', width: 140 },
		{ dataField: 'country', headerText: 'Country', width: 140 },
		{
			dataField: 'flag',
			headerText: 'Flag IMG',
			editable: false,
			prefix: `${PUBLIC_URL}/assets/`,
			renderer: { type: 'ImageRenderer', imgHeight: 24, altField: 'country' },
			width: 100
		},
		{ dataField: 'product', headerText: 'Product', width: 140 },
		{ dataField: 'color', headerText: 'Color', width: 100 },
		{
			dataField: 'price',
			headerText: 'Price',
			dataType: 'numeric',
			style: 'my-column',
			width: 120,
			editRenderer: { type: 'InputEditRenderer', onlyNumeric: true, textAlign: 'right', autoThousandSeparator: true }
		},
		{
			dataField: 'quantity',
			headerText: 'Quantity',
			dataType: 'numeric',
			style: 'my-column',
			width: 100,
			editRenderer: { type: 'InputEditRenderer', onlyNumeric: true, textAlign: 'right', autoThousandSeparator: true }
		},
		{ dataField: 'date', headerText: 'Date', dataType: 'date', dateInputFormat: 'yyyy-mm-dd', formatString: 'yyyy년 mm월 dd일' }
	];

	const gridProps = { width: '100%', height: 280 };

	const exportClick = () => {
		const grid = myGrid1.value;
		const grid2 = myGrid2.value;
		const grid3 = myGrid3.value;
		const grid4 = myGrid4.value;

		const exportProps = [
			{
				fileName: '그리드 4개 1개의 엑셀로 저장 테스트',
				sheetName: '일반 데이터',
				progressBar: true,
				headers: [
					{ text: '원본 데이터 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			},
			{
				sheetName: 'Type 1',
				headers: [
					{ text: 'Type 1 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			},
			{
				sheetName: 'Type 2',
				headers: [
					{ text: 'Type 2 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			},
			{
				sheetName: 'Type 3',
				headers: [
					{ text: 'Type 3 리스트', height: 24, style: { fontSize: 20, textAlign: 'center', fontWeight: 'bold', underline: true, background: '#DAD9FF' } },
					{ text: '', height: 5, style: { background: '#555555' } }
				]
			}
		];
		grid.exportToXlsxMulti([grid2.pid, grid3.pid, grid4.pid], exportProps);
	};

	onMounted(() => {
		myGrid1.value.setGridData(gridData);
		myGrid2.value.setGridData(gridData.slice(1, 3));
		myGrid3.value.setGridData(gridData.slice(2, 4));
		myGrid4.value.setGridData(gridData.slice(3, 5));
	});
</script>
<template>
	<div>
		<div class="desc">
			<button class="btn" @click="exportClick">4개 그리드 각각의 시트로 엑셀(xlsx) 저장하기</button>
		</div>
		<h3>그리드1</h3>
		<AUIGrid ref="myGrid1" :columnLayout="columnLayout" :gridProps="gridProps" />
		<h3>그리드2</h3>
		<AUIGrid ref="myGrid2" :columnLayout="columnLayout" :gridProps="gridProps" />
		<h3>그리드3</h3>
		<AUIGrid ref="myGrid3" :columnLayout="columnLayout" :gridProps="gridProps" />
		<h3>그리드4</h3>
		<AUIGrid ref="myGrid4" :columnLayout="columnLayout" :gridProps="gridProps" />
	</div>
</template>
