// samples-React.tsx/src/views/CodeBlock.tsx
import React, { useEffect, useRef, useState } from 'react';
import Prism from 'prismjs';
// Prism 1.30.0 Tomorrow와 예제에 사용하는 문법만 불러옵니다.
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-jsx';
import 'prismjs/components/prism-tsx';

export default function CodeBlock({ language = 'javascript', children }: { language?: string; children: string }) {
	const codeRef = useRef<HTMLElement>(null);
	const [feedback, setFeedback] = useState('');
	// React가 토큰 자식을 관리하지 않도록 원문 갱신과 강조를 이 영역에서만 처리합니다.
	useEffect(() => {
		if (!codeRef.current) return;
		codeRef.current.textContent = children;
		Prism.highlightElement(codeRef.current);
	}, [children, language]);
	// 토큰 HTML 대신 원문을 복사하고, 권한이 없으면 직접 복사할 영역을 선택합니다.
	async function copyCode() {
		try {
			await navigator.clipboard.writeText(children.trim());
			setFeedback('복사했습니다.');
		} catch (error) {
			const element = codeRef.current;
			if (!element) return;
			const range = document.createRange();
			range.selectNodeContents(element);
			const selection = window.getSelection();
			if (selection) { selection.removeAllRanges(); selection.addRange(range); }
			setFeedback('선택한 코드를 Ctrl+C 또는 ⌘C로 복사하세요.');
		}
	}
	return (
		<div className="demo-code-frame">
			<pre tabIndex={0} aria-label="코드 예제"><code className={`language-${language}`} ref={codeRef} /></pre>
			<div className="demo-code-tools">
				<span className="demo-code-feedback" role="status">{feedback}</span>
				<button type="button" className="demo-code-copy" onClick={copyCode}>코드 복사</button>
			</div>
		</div>
	);
}

// samples-Vue.ts/src/views/CodeBlock.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import Prism from 'prismjs';
// Prism 1.30.0 Tomorrow와 예제에 사용하는 문법만 불러옵니다.
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-jsx';
import 'prismjs/components/prism-tsx';

const props = defineProps<{ code: string; language?: string }>();
const codeBlock = ref<HTMLElement | null>(null);
const feedback = ref('');

// 슬롯 DOM과 Prism 토큰의 충돌을 피하고 원문이 변경된 경우에만 다시 강조합니다.
function highlight() {
	if (!codeBlock.value) return;
	codeBlock.value.textContent = props.code;
	Prism.highlightElement(codeBlock.value);
}
onMounted(highlight);
watch(() => [props.code, props.language], highlight, { flush: 'post' });
	// 토큰 HTML 대신 원문을 복사하고, 권한이 없으면 직접 복사할 영역을 선택합니다.
	async function copyCode() {
		try {
			await navigator.clipboard.writeText(props.code.trim());
			feedback.value = '복사했습니다.';
		} catch (error) {
			const element = codeBlock.value;
			if (!element) return;
			const range = document.createRange();
			range.selectNodeContents(element);
			const selection = window.getSelection();
			if (selection) { selection.removeAllRanges(); selection.addRange(range); }
			feedback.value = '선택한 코드를 Ctrl+C 또는 ⌘C로 복사하세요.';
		}
	}
</script>
<template>
	<div class="demo-code-frame">
		<pre tabindex="0" aria-label="코드 예제"><code :class="`language-${language || 'markup'}`" ref="codeBlock"></code></pre>
		<div class="demo-code-tools">
			<span class="demo-code-feedback" role="status">{{ feedback }}</span>
			<button type="button" class="demo-code-copy" @click="copyCode">코드 복사</button>
		</div>
	</div>
</template>
