// samples-Vue.js/src/samples/RendererTemplate.vue
<script>
	// AUIGrid 컴포넌트
	import AUIGrid from '../static/AUIGrid-Vue.js/AUIGrid.vue';
	import { gridData, selectList, checkboxGroup } from './data/RendererTemplateData';
	import { registerAUIGridTemplateHandler, unregisterAUIGridTemplateHandler } from '../static/AUIGrid-Vue.js/useAUIGridTemplateHandler';
	import './RendererTemplate.css';

	export default {
		components: {
			AUIGrid
		},

		data: () => ({
			// 그리드 속성 정의
			gridProps: {
				width: '100%',
				height: 480,
				// 행 높이 설정
				rowHeight: 34,
				editable: true,
				showStateColumn: true,
				selectionMode: 'multipleCells'
			},

			// 그리드 칼럼 레이아웃
			columnLayout: []
		}),
		created() {
			console.log('RendererTemplate 생성됨');
			this.columnLayout = [
				{
					dataField: 'name',
					headerText: 'Template-ButtonGroup',
					width: 260,
					renderer: {
						// HTML 템플릿 렌더러 사용
						type: 'TemplateRenderer'
					},
					labelFunction: (rowIndex, columnIndex, value) => {
						// HTML 템플릿 작성
						return `
							<div class="my_div">
								<span class="my_div_text_box">${value}</span>
								<span class="my_div_btn" onclick="myApplyBtnClick(${rowIndex}, event)">적용</span>
								<span class="my_div_btn2" onclick="myPopupBtnClick(${rowIndex}, event)">팝업</span>
							</div>
						`.trim();
					}
				},
				{
					dataField: 'code',
					headerText: 'Template-Select',
					width: 280,
					editable: false, // 그리드의 에디팅 사용 안함( 템플릿에서 만든 Select 로 에디팅 처리 하기 위함 )
					renderer: {
						// HTML 템플릿 렌더러 사용
						type: 'TemplateRenderer'
					},
					labelFunction: (rowIndex, columnIndex, value) => {
						// HTML 템플릿 작성
						if (!value) return '';
						if (value === 'None') {
							return `
								<div class="my_div">
									<span style="line-height:2em;">
									선택할 수 없도록 작성됨(즉, 동적 select 표현)
									</span>
								</div>
							`.trim();
						}

						// option 만들기
						const options = selectList
							.map(({ value: code, text }) => {
								const selected = code === value ? ' selected="selected"' : '';
								return `<option value="${code}"${selected}>${text}</option>`;
							})
							.join('');

						return `
							<div class="my_div">
								<span class="my_div_code_span">코드명 : ${value}</span>
								<select class="my_select" onchange="mySelectChangeHandler(${rowIndex}, this.value, event);">
									${options}
								</select>
							</div>
						`.trim();
					}
				},
				{
					dataField: 'check',
					headerText: 'Template-CheckGroup',
					width: 180,
					editable: false, // 그리드의 에디팅 사용 안함( 템플릿에서 만든 Select 로 에디팅 처리 하기 위함 )
					renderer: {
						// HTML 템플릿 렌더러 사용
						type: 'TemplateRenderer'
					},
					// dataField 로 정의된 필드 값이 HTML 이라면 labelFunction 으로 처리할 필요 없음.
					labelFunction: (rowIndex, columnIndex, value) => {
						// HTML 템플릿 작성
						const selectedValues = value.split(',');

						// 체크박스 개수에 맞게 만들기
						const checkboxes = checkboxGroup
							.map(({ value, label }) => {
								const isChecked = selectedValues.includes(value) ? 'checked="checked"' : '';
								return `<label><input type="checkbox" value="${value}" ${isChecked} onclick="myCheckClick(${rowIndex}, event);">${label}</label>`;
							})
							.join('');

						return `
							<div class="my_div">
								<span class="my_div_chk_span">
									${checkboxes}
								</span>
							</div>
						`.trim();
					}
				}
			];
		},

		mounted() {
			console.log('RendererTemplate 마운트됨');
			const grid = this.$refs.myGrid;
			grid.setGridData(gridData);

			// TemplateRenderer 에서 사용하는 함수들 등록 하기
			registerAUIGridTemplateHandler('myApplyBtnClick', this.myApplyBtnClick);
			registerAUIGridTemplateHandler('myPopupBtnClick', this.myPopupBtnClick);
			registerAUIGridTemplateHandler('mySelectChangeHandler', this.mySelectChangeHandler);
			registerAUIGridTemplateHandler('myCheckClick', this.myCheckClick);
		},

		unmounted() {
			console.log('RendererTemplate 언마운트됨');

			// TemplateRenderer 에서 사용하는 함수들 등록 해제 하기
			unregisterAUIGridTemplateHandler('myApplyBtnClick');
			unregisterAUIGridTemplateHandler('myPopupBtnClick');
			unregisterAUIGridTemplateHandler('mySelectChangeHandler');
			unregisterAUIGridTemplateHandler('myCheckClick');
		},
		methods: {
			// 수정으로 진입함.
			calIconClick() {
				const grid = this.$refs.myGrid;
				grid.openInputer();
			},

			// 그리드 템플릿 렌더러 적용 버튼 클릭
			myApplyBtnClick(rowIndex, event) {
				const grid = this.$refs.myGrid;
				grid.updateRow(
					{
						name: '셀 값 예약어로 수정'
					},
					rowIndex
				);
				alert(`eventType : ${event.type}, rowIndex : ${rowIndex} 적용 버턴 클릭`);
			},

			// 그리드 템플릿 렌더러 팝업 버튼 클릭
			myPopupBtnClick(rowIndex) {
				alert('rowIndex : ' + rowIndex + ' 팝업 버턴 클릭');
			},

			// 그리드 템플릿 렌더러 select 변경
			mySelectChangeHandler(rowIndex, selectedValue) {
				alert(selectedValue);
				const grid = this.$refs.myGrid;
				// 그리드에 실제 업데이트 적용 시킴
				grid.updateRow(
					{
						code: selectedValue
					},
					rowIndex
				);
			},

			// 그리드 템플릿 렌더러 체크박스 클릭
			myCheckClick(rowIndex, event) {
				const target = event.target;
				const grid = this.$refs.myGrid;
				alert('rowIndex : ' + rowIndex + ', value : ' + target.value + ', checked : ' + target.checked);

				// 해당 행의 아이템 얻기
				const item = grid.getItemByRowIndex(rowIndex);
				const checkValue = item.check;
				const checkArr = checkValue.split(',');

				// 체크된 경우 포함시킴
				if (target.checked) {
					checkArr.push(target.value);
				} else {
					// 해제된 경우 제거함.
					checkArr.splice(checkArr.indexOf(target.value), 1);
				}

				// 그리드 값 수정함.
				grid.updateRow(
					{
						check: checkArr.join(',')
					},
					rowIndex
				);
			}
		}
	};
</script>
<template>
	<div>
		<div class="desc">
			<p>데이터 값이 HTML 인 경우 그대로 출력하며, 사용자가 임의로 labelFunction 에서 HTML 스트링을 작성할 수 있습니다.(innerHTML 처리)</p>
			<strong>템플릿 렌더러에서 수정 가능한 태그를 어떻게 작성하는지를 보여주는 데모입니다.</strong>
			<p>템플릿 렌더러로 작성된 데이터 수정도 Undo(Ctrl+Z), Redo(Ctrl+Y) 를 지원합니다.</p>
			<p>HTML 템플릿은 행 높이를 벗어날 수 없습니다. 예를 들어 br 태그로 개행을 한다해도 지정된 행 높이를 벗어 날 수 없습니다.(그리드의 rowHeight 속성으로 높이를 크게 하십시오.)</p>
			<p>■ 단점 : 사용자가 HTML 템플릿을 작성하였기 때문에 엑셀 저장, 그룹핑, 필터링, 정렬 등에 제약을 받습니다. (dataField 값 기준으로 처리됩니다.)</p>
			<p><strong>템플릿 렌더러(TempalateRenderer)를 Vue.js 와 같은 프로젝트에서 사용을 추천하지 않습니다. CustomRenderer를 사용하십시오.</strong></p>
		</div>
		<AUIGrid ref="myGrid" :columnLayout="columnLayout" :gridProps="gridProps" />
	</div>
</template>

// samples-React.js/src/samples/RendererTemplate.js
import React, { useEffect, useRef } from 'react';
import AUIGrid from '../static/AUIGrid-React.js/AUIGridReact';
import { gridData, selectList, checkboxGroup } from './data/RendererTemplateData';
import { registerAUIGridTemplateHandler, unregisterAUIGridTemplateHandler } from './useAUIGridTemplateHandler';
import './RendererTemplate.css';

const RendererTemplate = () => {
	// 그리드 객체
	const myGrid = useRef();

	// 그리드 이름, SPA 프로젝트일 때 해당 그리드는 중복되어선 안됨.
	const gridName = 'RendererTemplate';

	// 그리드 칼럼 레이아웃 정의
	const columnLayout = [
		{
			dataField: 'name',
			headerText: 'Template-ButtonGroup',
			width: 260,
			renderer: {
				// HTML 템플릿 렌더러 사용
				type: 'TemplateRenderer'
			},
			// dataField 로 정의된 필드 값이 HTML 이라면 labelFunction 으로 처리할 필요 없음.
			labelFunction: (rowIndex, columnIndex, value, headerText, item) => {
				// HTML 템플릿 작성
				return `
					<div class="my_div">
						<span class="my_div_text_box">${value}</span>
						<span class="my_div_btn" onclick="myApplyBtnClick(${rowIndex}, event)">적용</span>
						<span class="my_div_btn2" onclick="myPopupBtnClick(${rowIndex}, event)">팝업</span>
					</div>
				`.trim();
			}
		},
		{
			dataField: 'code',
			headerText: 'Template-Select',
			width: 280,
			editable: false, // 그리드의 에디팅 사용 안함( 템플릿에서 만든 Select 로 에디팅 처리 하기 위함 )
			renderer: {
				// HTML 템플릿 렌더러 사용
				type: 'TemplateRenderer'
			},
			// dataField 로 정의된 필드 값이 HTML 이라면 labelFunction 으로 처리할 필요 없음.
			labelFunction: (rowIndex, columnIndex, value, headerText, item) => {
				// HTML 템플릿 작성
				if (!value) return '';
				if (value === 'None') {
					return `
						<div class="my_div">
							<span style="line-height:2em;">
							선택할 수 없도록 작성됨(즉, 동적 select 표현)
							</span>
						</div>
					`.trim();
				}

				// option 만들기
				const options = selectList
					.map(({ value: code, text }) => {
						const selected = code === value ? ' selected="selected"' : '';
						return `<option value="${code}"${selected}>${text}</option>`;
					})
					.join('');

				return `
					<div class="my_div">
						<span class="my_div_code_span">코드명 : ${value}</span>
						<select class="my_select" onchange="mySelectChangeHandler(${rowIndex}, this.value, event);">
							${options}
						</select>
					</div>
				`.trim();
			}
		},
		{
			dataField: 'check',
			headerText: 'Template-CheckGroup',
			width: 180,
			editable: false, // 그리드의 에디팅 사용 안함( 템플릿에서 만든 Select 로 에디팅 처리 하기 위함 )
			renderer: {
				// HTML 템플릿 렌더러 사용
				type: 'TemplateRenderer'
			},
			// dataField 로 정의된 필드 값이 HTML 이라면 labelFunction 으로 처리할 필요 없음.
			labelFunction: (rowIndex, columnIndex, value, headerText, item) => {
				// HTML 템플릿 작성
				const selectedValues = value.split(',');

				// 체크박스 개수에 맞게 만들기
				const checkboxes = checkboxGroup
					.map(({ value, label }) => {
						const isChecked = selectedValues.includes(value) ? 'checked="checked"' : '';
						return `<label><input type="checkbox" value="${value}" ${isChecked} onclick="myCheckClick(${rowIndex}, event);">${label}</label>`;
					})
					.join('');

				return `
					<div class="my_div">
						<span class="my_div_chk_span">
							${checkboxes}
						</span>
					</div>
				`.trim();
			}
		}
	];

	// 그리드 속성 정의
	const gridProps = {
		width: '100%',
		height: 480,
		// 행 높이 설정
		rowHeight: 34,
		editable: true,
		showStateColumn: true,
		selectionMode: 'multipleCells'
	};

	useEffect(() => {
		console.log('RendererTemplate 마운트됨');
		// TemplateRenderer 에서 사용하는 함수들 등록 하기
		registerAUIGridTemplateHandler('myApplyBtnClick', myApplyBtnClick);
		registerAUIGridTemplateHandler('myPopupBtnClick', myPopupBtnClick);
		registerAUIGridTemplateHandler('mySelectChangeHandler', mySelectChangeHandler);
		registerAUIGridTemplateHandler('myCheckClick', myCheckClick);

		const grid = myGrid.current;
		grid.setGridData(gridData);
		return () => {
			console.log('RendererTemplate 언마운트됨');
			// TemplateRenderer 에서 사용하는 함수들 등록 해제 하기
			unregisterAUIGridTemplateHandler('myApplyBtnClick');
			unregisterAUIGridTemplateHandler('myPopupBtnClick');
			unregisterAUIGridTemplateHandler('mySelectChangeHandler');
			unregisterAUIGridTemplateHandler('myCheckClick');
		};
	}, []);

	// 그리드 템플릿 렌더러 적용 버튼 클릭
	const myApplyBtnClick = (rowIndex, event) => {
		const grid = myGrid.current;
		grid.updateRow(
			{
				name: '셀 값 예약어로 수정'
			},
			rowIndex
		);
		alert(`eventType : ${event.type}, rowIndex : ${rowIndex} 적용 버턴 클릭`);
	};

	// 그리드 템플릿 렌더러 팝업 버튼 클릭
	const myPopupBtnClick = (rowIndex) => {
		alert('rowIndex : ' + rowIndex + ' 팝업 버턴 클릭');
	};

	// 그리드 템플릿 렌더러 select 변경
	const mySelectChangeHandler = (rowIndex, selectedValue) => {
		alert(selectedValue);
		const grid = myGrid.current;
		// 그리드에 실제 업데이트 적용 시킴
		grid.updateRow(
			{
				code: selectedValue
			},
			rowIndex
		);
	};

	// 그리드 템플릿 렌더러 체크박스 클릭
	const myCheckClick = (rowIndex, event) => {
		const target = event.target;
		const grid = myGrid.current;
		alert('rowIndex : ' + rowIndex + ', value : ' + target.value + ', checked : ' + target.checked);

		// 해당 행의 아이템 얻기
		const item = grid.getItemByRowIndex(rowIndex);
		const checkValue = item.check;
		const checkArr = checkValue.split(',');

		// 체크된 경우 포함시킴
		if (target.checked) {
			checkArr.push(target.value);
		} else {
			// 해제된 경우 제거함.
			checkArr.splice(checkArr.indexOf(target.value), 1);
		}

		// 그리드 값 수정함.
		grid.updateRow(
			{
				check: checkArr.join(',')
			},
			rowIndex
		);
	};

	return (
		<div>
			<div className="desc">
				<p>데이터 값이 HTML 인 경우 그대로 출력하며, 사용자가 임의로 labelFunction 에서 HTML 스트링을 작성할 수 있습니다.(innerHTML 처리)</p>
				<strong>템플릿 렌더러에서 수정 가능한 태그를 어떻게 작성하는지를 보여주는 데모입니다.</strong>
				<p>템플릿 렌더러로 작성된 데이터 수정도 Undo(Ctrl+Z), Redo(Ctrl+Y) 를 지원합니다.</p>
				<p>HTML 템플릿은 행 높이를 벗어날 수 없습니다. 예를 들어 br 태그로 개행을 한다해도 지정된 행 높이를 벗어 날 수 없습니다.(그리드의 rowHeight 속성으로 높이를 크게 하십시오.)</p>
				<p>■ 단점 : 사용자가 HTML 템플릿을 작성하였기 때문에 엑셀 저장, 그룹핑, 필터링, 정렬 등에 제약을 받습니다. (dataField 값 기준으로 처리됩니다.)</p>
				<p>
					<strong>템플릿 렌더러(TempalateRenderer)를 React.js 와 같은 프로젝트에서 사용을 추천하지 않습니다. CustomRenderer를 사용하십시오.</strong>
				</p>
			</div>
			<AUIGrid ref={myGrid} name={gridName} columnLayout={columnLayout} gridProps={gridProps} />
		</div>
	);
};

export default RendererTemplate;
